"""
Research agent state definition.

ResearchState is a TypedDict that serves as the single source of truth
for the entire LangGraph research workflow.  Every node reads from and
writes to this shared state — no side-channels, no unrelated variables.

State fields
------------
query              Original user question
plan               Sub-tasks generated by the planner node
current_task       The sub-task currently being processed
retrieved_chunks   Aggregated retrieval results (list of dicts)
findings           Structured findings produced by the analyzer
report             Final research report from the report writer
sources            Deduplicated citation metadata
retry_count        Number of retrieval retries performed (max MAX_RETRIES)
status             Current phase of execution
"""

from typing import TypedDict


MAX_RETRIES: int = 3

VALID_STATUSES = frozenset(
    {
        "planning",
        "retrieving",
        "analyzing",
        "writing",
        "complete",
        "partial",
    }
)


class ResearchState(TypedDict):
    """Shared state flowing through every node in the research graph."""

    query: str
    plan: list[str]
    current_task: str
    retrieved_chunks: list[dict]
    findings: list[str]
    report: str
    sources: list[dict]
    retry_count: int
    average_similarity: float
    status: str
